// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	OrderItems        string
	Orders            string
	PaymentDetails    string
	Payments          string
	ProductCategories string
	Products          string
	SchemaMigrations  string
	Users             string
}{
	OrderItems:        "order_items",
	Orders:            "orders",
	PaymentDetails:    "payment_details",
	Payments:          "payments",
	ProductCategories: "product_categories",
	Products:          "products",
	SchemaMigrations:  "schema_migrations",
	Users:             "users",
}
